before_script:
    - curl -o libardsim-last.tar.gz https://ci.yapbreak.fr/job/libraries/job/LibArdsim/lastSuccessfulBuild/artifact/libardsim-last.tar.gz
    - tar xzf libardsim-last.tar.gz
    - (cd libardsim-*/ && ./configure --prefix=/tmp/libardsim && make && make install)
    - rm -rf libardsim-*
    - ./bootstrap.sh

stages:
    - build

build:
    stage: build
    script:
        - PKG_CONFIG_PATH=/tmp/libardsim/lib/pkgconfig ./configure
        - make
        - make firmware
        - make clean
        - PKG_CONFIG_PATH=/tmp/libardsim/lib/pkgconfig ./configure --enable-coverage
        - make coverage | tail -10
